### ISSUE TITLE
Supporting CPC-type games

### ISSUE THREAD

**Issue by mbaroni** [facebookresearch/EGG#164] opened 2020-11-16 21:43 UTC
### Is your proposal related to a problem?

Discriminative emergence games are very close to the idea of contrastive predictive coding in computer vision, and it would be cool to support code for comparative experiments in EGG, in particular along the lines of https://arxiv.org/abs/1905.09272

### Describe the solution you'd like to have implemented

Add code to support experiments with learning image representations using a discrete channel communication game.

**Comment by eugene-kharitonov** [comment] 2021-02-05 18:20
Seems like a near duplicate of https://github.com/facebookresearch/EGG/issues/185

**Comment by robertodessi** [comment] 2021-02-17 12:22
Closing as it seems a duplicate. @mbaroni feel free to reopen if we are missing something

**Closed by robertodessi** 2021-02-17 12:22 UTC
Labels: major-new-functionality
